// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DataNodeClient is the client API for DataNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeClient interface {
	UpploadChunks(ctx context.Context, opts ...grpc.CallOption) (DataNode_UpploadChunksClient, error)
	DowloadChunks(ctx context.Context, in *RequestChunk, opts ...grpc.CallOption) (*Chunk, error)
	ProposalRequest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
}

type dataNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeClient(cc grpc.ClientConnInterface) DataNodeClient {
	return &dataNodeClient{cc}
}

func (c *dataNodeClient) UpploadChunks(ctx context.Context, opts ...grpc.CallOption) (DataNode_UpploadChunksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataNode_serviceDesc.Streams[0], "/pb.DataNode/UpploadChunks", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataNodeUpploadChunksClient{stream}
	return x, nil
}

type DataNode_UpploadChunksClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type dataNodeUpploadChunksClient struct {
	grpc.ClientStream
}

func (x *dataNodeUpploadChunksClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataNodeUpploadChunksClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataNodeClient) DowloadChunks(ctx context.Context, in *RequestChunk, opts ...grpc.CallOption) (*Chunk, error) {
	out := new(Chunk)
	err := c.cc.Invoke(ctx, "/pb.DataNode/DowloadChunks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeClient) ProposalRequest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.DataNode/ProposalRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataNodeServer is the server API for DataNode service.
// All implementations must embed UnimplementedDataNodeServer
// for forward compatibility
type DataNodeServer interface {
	UpploadChunks(DataNode_UpploadChunksServer) error
	DowloadChunks(context.Context, *RequestChunk) (*Chunk, error)
	ProposalRequest(context.Context, *Empty) (*Response, error)
	mustEmbedUnimplementedDataNodeServer()
}

// UnimplementedDataNodeServer must be embedded to have forward compatible implementations.
type UnimplementedDataNodeServer struct {
}

func (UnimplementedDataNodeServer) UpploadChunks(DataNode_UpploadChunksServer) error {
	return status.Errorf(codes.Unimplemented, "method UpploadChunks not implemented")
}
func (UnimplementedDataNodeServer) DowloadChunks(context.Context, *RequestChunk) (*Chunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DowloadChunks not implemented")
}
func (UnimplementedDataNodeServer) ProposalRequest(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposalRequest not implemented")
}
func (UnimplementedDataNodeServer) mustEmbedUnimplementedDataNodeServer() {}

// UnsafeDataNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeServer will
// result in compilation errors.
type UnsafeDataNodeServer interface {
	mustEmbedUnimplementedDataNodeServer()
}

func RegisterDataNodeServer(s *grpc.Server, srv DataNodeServer) {
	s.RegisterService(&_DataNode_serviceDesc, srv)
}

func _DataNode_UpploadChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataNodeServer).UpploadChunks(&dataNodeUpploadChunksServer{stream})
}

type DataNode_UpploadChunksServer interface {
	SendAndClose(*Response) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type dataNodeUpploadChunksServer struct {
	grpc.ServerStream
}

func (x *dataNodeUpploadChunksServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataNodeUpploadChunksServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DataNode_DowloadChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServer).DowloadChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DataNode/DowloadChunks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServer).DowloadChunks(ctx, req.(*RequestChunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNode_ProposalRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServer).ProposalRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DataNode/ProposalRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServer).ProposalRequest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DataNode",
	HandlerType: (*DataNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DowloadChunks",
			Handler:    _DataNode_DowloadChunks_Handler,
		},
		{
			MethodName: "ProposalRequest",
			Handler:    _DataNode_ProposalRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpploadChunks",
			Handler:       _DataNode_UpploadChunks_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "Lab_2.proto",
}

// NameNodeClient is the client API for NameNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NameNodeClient interface {
	WriteLog(ctx context.Context, in *Write, opts ...grpc.CallOption) (*Response, error)
	FinalProposal(ctx context.Context, in *Proposal, opts ...grpc.CallOption) (*Proposal, error)
	FileRequest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NameNode_FileRequestClient, error)
	AddressRequest(ctx context.Context, in *File, opts ...grpc.CallOption) (*ChunkAddress, error)
}

type nameNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNameNodeClient(cc grpc.ClientConnInterface) NameNodeClient {
	return &nameNodeClient{cc}
}

func (c *nameNodeClient) WriteLog(ctx context.Context, in *Write, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.NameNode/WriteLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeClient) FinalProposal(ctx context.Context, in *Proposal, opts ...grpc.CallOption) (*Proposal, error) {
	out := new(Proposal)
	err := c.cc.Invoke(ctx, "/pb.NameNode/FinalProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeClient) FileRequest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NameNode_FileRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NameNode_serviceDesc.Streams[0], "/pb.NameNode/FileRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &nameNodeFileRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NameNode_FileRequestClient interface {
	Recv() (*File, error)
	grpc.ClientStream
}

type nameNodeFileRequestClient struct {
	grpc.ClientStream
}

func (x *nameNodeFileRequestClient) Recv() (*File, error) {
	m := new(File)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nameNodeClient) AddressRequest(ctx context.Context, in *File, opts ...grpc.CallOption) (*ChunkAddress, error) {
	out := new(ChunkAddress)
	err := c.cc.Invoke(ctx, "/pb.NameNode/AddressRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameNodeServer is the server API for NameNode service.
// All implementations must embed UnimplementedNameNodeServer
// for forward compatibility
type NameNodeServer interface {
	WriteLog(context.Context, *Write) (*Response, error)
	FinalProposal(context.Context, *Proposal) (*Proposal, error)
	FileRequest(*Empty, NameNode_FileRequestServer) error
	AddressRequest(context.Context, *File) (*ChunkAddress, error)
	mustEmbedUnimplementedNameNodeServer()
}

// UnimplementedNameNodeServer must be embedded to have forward compatible implementations.
type UnimplementedNameNodeServer struct {
}

func (UnimplementedNameNodeServer) WriteLog(context.Context, *Write) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteLog not implemented")
}
func (UnimplementedNameNodeServer) FinalProposal(context.Context, *Proposal) (*Proposal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalProposal not implemented")
}
func (UnimplementedNameNodeServer) FileRequest(*Empty, NameNode_FileRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method FileRequest not implemented")
}
func (UnimplementedNameNodeServer) AddressRequest(context.Context, *File) (*ChunkAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressRequest not implemented")
}
func (UnimplementedNameNodeServer) mustEmbedUnimplementedNameNodeServer() {}

// UnsafeNameNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameNodeServer will
// result in compilation errors.
type UnsafeNameNodeServer interface {
	mustEmbedUnimplementedNameNodeServer()
}

func RegisterNameNodeServer(s *grpc.Server, srv NameNodeServer) {
	s.RegisterService(&_NameNode_serviceDesc, srv)
}

func _NameNode_WriteLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Write)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServer).WriteLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NameNode/WriteLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServer).WriteLog(ctx, req.(*Write))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNode_FinalProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServer).FinalProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NameNode/FinalProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServer).FinalProposal(ctx, req.(*Proposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNode_FileRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NameNodeServer).FileRequest(m, &nameNodeFileRequestServer{stream})
}

type NameNode_FileRequestServer interface {
	Send(*File) error
	grpc.ServerStream
}

type nameNodeFileRequestServer struct {
	grpc.ServerStream
}

func (x *nameNodeFileRequestServer) Send(m *File) error {
	return x.ServerStream.SendMsg(m)
}

func _NameNode_AddressRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServer).AddressRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NameNode/AddressRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServer).AddressRequest(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

var _NameNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NameNode",
	HandlerType: (*NameNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteLog",
			Handler:    _NameNode_WriteLog_Handler,
		},
		{
			MethodName: "FinalProposal",
			Handler:    _NameNode_FinalProposal_Handler,
		},
		{
			MethodName: "AddressRequest",
			Handler:    _NameNode_AddressRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileRequest",
			Handler:       _NameNode_FileRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Lab_2.proto",
}
